In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [3]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [7]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [9]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [10]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(filepath=checkpoint_path,
                              verbose=1,
                              save_weights_only=True,
                              save_freq=1000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
35/35 [==============================] - 0s 835us/step - loss: 0.5624 - accuracy: 0.7423
Epoch 2/100
35/35 [==============================] - 0s 875us/step - loss: 0.5051 - accuracy: 0.7976
Epoch 3/100
35/35 [==============================] - 0s 742us/step - loss: 0.4679 - accuracy: 0.8185
Epoch 4/100
35/35 [==============================] - 0s 704us/step - loss: 0.4408 - accuracy: 0.8294
Epoch 5/100
35/35 [==============================] - 0s 725us/step - loss: 0.4208 - accuracy: 0.8303
Epoch 6/100
35/35 [==============================] - 0s 692us/step - loss: 0.4041 - accuracy: 0.8348
Epoch 7/100
35/35 [==============================] - 0s 629us/step - loss: 0.3899 - accuracy: 0.8403
Epoch 8/100
35/35 [==============================] - 0s 710us/step - loss: 0.3769 - accuracy: 0.8521
Epoch 9/100
35/35 [==============================] - 0s 636us/step - loss: 0.3644 - accuracy: 0.8566
Epoch 10/100
35/35 [==============================] - 0s 751us/step - loss: 0.3517 - accuracy: 0.8666
Epoch 11/100
35/35 [==============================] - 0s 667us/step - loss: 0.3402 - accuracy: 0.8784
Epoch 12/100
35/35 [==============================] - 0s 659us/step - loss: 0.3283 - accuracy: 0.8829
Epoch 13/100
35/35 [==============================] - 0s 747us/step - loss: 0.3180 - accuracy: 0.8893
Epoch 14/100
35/35 [==============================] - 0s 731us/step - loss: 0.3077 - accuracy: 0.8920
Epoch 15/100
35/35 [==============================] - 0s 711us/step - loss: 0.2994 - accuracy: 0.8911
Epoch 16/100
35/35 [==============================] - 0s 730us/step - loss: 0.2905 - accuracy: 0.9002
Epoch 17/100
35/35 [==============================] - 0s 653us/step - loss: 0.2836 - accuracy: 0.9011
Epoch 18/100
35/35 [==============================] - 0s 685us/step - loss: 0.2779 - accuracy: 0.9020
Epoch 19/100
35/35 [==============================] - 0s 681us/step - loss: 0.2720 - accuracy: 0.9002
Epoch 20/100
35/35 [==============================] - 0s 690us/step - loss: 0.2673 - accuracy: 0.9020
Epoch 21/100
35/35 [==============================] - 0s 722us/step - loss: 0.2627 - accuracy: 0.9029
Epoch 22/100
35/35 [==============================] - 0s 689us/step - loss: 0.2585 - accuracy: 0.9002
Epoch 23/100
35/35 [==============================] - 0s 698us/step - loss: 0.2547 - accuracy: 0.8993
Epoch 24/100
35/35 [==============================] - 0s 755us/step - loss: 0.2516 - accuracy: 0.9020
Epoch 25/100
35/35 [==============================] - 0s 711us/step - loss: 0.2479 - accuracy: 0.9002
Epoch 26/100
35/35 [==============================] - 0s 675us/step - loss: 0.2451 - accuracy: 0.9020
Epoch 27/100
35/35 [==============================] - 0s 765us/step - loss: 0.2416 - accuracy: 0.9029
Epoch 28/100
35/35 [==============================] - 0s 718us/step - loss: 0.2386 - accuracy: 0.9020
Epoch 29/100
 1/35 [..............................] - ETA: 0s - loss: 0.3388 - accuracy: 0.8438
Epoch 00029: saving model to checkpoints/weights.29.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.2358 - accuracy: 0.9038
Epoch 30/100
35/35 [==============================] - 0s 714us/step - loss: 0.2330 - accuracy: 0.9065
Epoch 31/100
35/35 [==============================] - 0s 727us/step - loss: 0.2303 - accuracy: 0.9056
Epoch 32/100
35/35 [==============================] - 0s 686us/step - loss: 0.2275 - accuracy: 0.9065
Epoch 33/100
35/35 [==============================] - 0s 642us/step - loss: 0.2250 - accuracy: 0.9093
Epoch 34/100
35/35 [==============================] - 0s 730us/step - loss: 0.2218 - accuracy: 0.9083
Epoch 35/100
35/35 [==============================] - 0s 695us/step - loss: 0.2201 - accuracy: 0.9093
Epoch 36/100
35/35 [==============================] - 0s 809us/step - loss: 0.2176 - accuracy: 0.9129
Epoch 37/100
35/35 [==============================] - 0s 806us/step - loss: 0.2152 - accuracy: 0.9120
Epoch 38/100
35/35 [==============================] - 0s 782us/step - loss: 0.2135 - accuracy: 0.9138
Epoch 39/100
35/35 [==============================] - 0s 803us/step - loss: 0.2110 - accuracy: 0.9120
Epoch 40/100
35/35 [==============================] - 0s 808us/step - loss: 0.2080 - accuracy: 0.9165
Epoch 41/100
35/35 [==============================] - 0s 794us/step - loss: 0.2055 - accuracy: 0.9192
Epoch 42/100
35/35 [==============================] - 0s 780us/step - loss: 0.2035 - accuracy: 0.9174
Epoch 43/100
35/35 [==============================] - 0s 764us/step - loss: 0.2007 - accuracy: 0.9201
Epoch 44/100
35/35 [==============================] - 0s 802us/step - loss: 0.1991 - accuracy: 0.9183
Epoch 45/100
35/35 [==============================] - 0s 774us/step - loss: 0.1971 - accuracy: 0.9192
Epoch 46/100
35/35 [==============================] - 0s 739us/step - loss: 0.1952 - accuracy: 0.9192
Epoch 47/100
35/35 [==============================] - 0s 794us/step - loss: 0.1923 - accuracy: 0.9220
Epoch 48/100
35/35 [==============================] - 0s 706us/step - loss: 0.1908 - accuracy: 0.9220
Epoch 49/100
35/35 [==============================] - 0s 639us/step - loss: 0.1891 - accuracy: 0.9247
Epoch 50/100
35/35 [==============================] - 0s 744us/step - loss: 0.1874 - accuracy: 0.9220
Epoch 51/100
35/35 [==============================] - 0s 821us/step - loss: 0.1847 - accuracy: 0.9238
Epoch 52/100
35/35 [==============================] - 0s 740us/step - loss: 0.1834 - accuracy: 0.9247
Epoch 53/100
35/35 [==============================] - 0s 734us/step - loss: 0.1811 - accuracy: 0.9247
Epoch 54/100
35/35 [==============================] - 0s 675us/step - loss: 0.1803 - accuracy: 0.9247
Epoch 55/100
35/35 [==============================] - 0s 722us/step - loss: 0.1786 - accuracy: 0.9274
Epoch 56/100
35/35 [==============================] - 0s 666us/step - loss: 0.1760 - accuracy: 0.9283
Epoch 57/100
35/35 [==============================] - 0s 690us/step - loss: 0.1754 - accuracy: 0.9292
Epoch 58/100
 1/35 [..............................] - ETA: 0s - loss: 0.0655 - accuracy: 1.0000
Epoch 00058: saving model to checkpoints/weights.58.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1723 - accuracy: 0.9319
Epoch 59/100
35/35 [==============================] - 0s 681us/step - loss: 0.1704 - accuracy: 0.9328
Epoch 60/100
35/35 [==============================] - 0s 641us/step - loss: 0.1697 - accuracy: 0.9319
Epoch 61/100
35/35 [==============================] - 0s 711us/step - loss: 0.1684 - accuracy: 0.9365
Epoch 62/100
35/35 [==============================] - 0s 690us/step - loss: 0.1668 - accuracy: 0.9356
Epoch 63/100
35/35 [==============================] - 0s 737us/step - loss: 0.1640 - accuracy: 0.9338
Epoch 64/100
35/35 [==============================] - 0s 724us/step - loss: 0.1626 - accuracy: 0.9383
Epoch 65/100
35/35 [==============================] - 0s 675us/step - loss: 0.1602 - accuracy: 0.9456
Epoch 66/100
35/35 [==============================] - 0s 709us/step - loss: 0.1588 - accuracy: 0.9410
Epoch 67/100
35/35 [==============================] - 0s 704us/step - loss: 0.1571 - accuracy: 0.9410
Epoch 68/100
35/35 [==============================] - 0s 658us/step - loss: 0.1553 - accuracy: 0.9456
Epoch 69/100
35/35 [==============================] - 0s 703us/step - loss: 0.1541 - accuracy: 0.9428
Epoch 70/100
35/35 [==============================] - 0s 691us/step - loss: 0.1535 - accuracy: 0.9446
Epoch 71/100
35/35 [==============================] - 0s 682us/step - loss: 0.1517 - accuracy: 0.9456
Epoch 72/100
35/35 [==============================] - 0s 771us/step - loss: 0.1500 - accuracy: 0.9501
Epoch 73/100
35/35 [==============================] - 0s 693us/step - loss: 0.1481 - accuracy: 0.9465
Epoch 74/100
35/35 [==============================] - 0s 669us/step - loss: 0.1471 - accuracy: 0.9492
Epoch 75/100
35/35 [==============================] - 0s 651us/step - loss: 0.1443 - accuracy: 0.9537
Epoch 76/100
35/35 [==============================] - 0s 745us/step - loss: 0.1437 - accuracy: 0.9510
Epoch 77/100
35/35 [==============================] - 0s 753us/step - loss: 0.1421 - accuracy: 0.9519
Epoch 78/100

35/35 [==============================] - 0s 683us/step - loss: 0.1411 - accuracy: 0.9501
Epoch 79/100
35/35 [==============================] - 0s 734us/step - loss: 0.1399 - accuracy: 0.9510
Epoch 80/100
35/35 [==============================] - 0s 673us/step - loss: 0.1388 - accuracy: 0.9546
Epoch 81/100
35/35 [==============================] - 0s 672us/step - loss: 0.1375 - accuracy: 0.9564
Epoch 82/100
35/35 [==============================] - 0s 639us/step - loss: 0.1365 - accuracy: 0.9555
Epoch 83/100
35/35 [==============================] - 0s 718us/step - loss: 0.1341 - accuracy: 0.9555
Epoch 84/100
35/35 [==============================] - 0s 624us/step - loss: 0.1328 - accuracy: 0.9583
Epoch 85/100
35/35 [==============================] - 0s 690us/step - loss: 0.1322 - accuracy: 0.9555
Epoch 86/100
 1/35 [..............................] - ETA: 0s - loss: 0.0695 - accuracy: 1.0000
Epoch 00086: saving model to checkpoints/weights.86.hdf5
35/35 [==============================] - 0s 945us/step - loss: 0.1312 - accuracy: 0.9574
Epoch 87/100
35/35 [==============================] - 0s 700us/step - loss: 0.1297 - accuracy: 0.9564
Epoch 88/100
35/35 [==============================] - 0s 640us/step - loss: 0.1290 - accuracy: 0.9583
Epoch 89/100
35/35 [==============================] - 0s 660us/step - loss: 0.1270 - accuracy: 0.9583
Epoch 90/100
35/35 [==============================] - 0s 706us/step - loss: 0.1256 - accuracy: 0.9601
Epoch 91/100
35/35 [==============================] - 0s 686us/step - loss: 0.1247 - accuracy: 0.9583
Epoch 92/100
35/35 [==============================] - 0s 630us/step - loss: 0.1242 - accuracy: 0.9592
Epoch 93/100
35/35 [==============================] - 0s 666us/step - loss: 0.1226 - accuracy: 0.9574
Epoch 94/100
35/35 [==============================] - 0s 632us/step - loss: 0.1205 - accuracy: 0.9610
Epoch 95/100
35/35 [==============================] - 0s 703us/step - loss: 0.1206 - accuracy: 0.9601
Epoch 96/100
35/35 [==============================] - 0s 638us/step - loss: 0.1199 - accuracy: 0.9610
Epoch 97/100
35/35 [==============================] - 0s 658us/step - loss: 0.1183 - accuracy: 0.9592
Epoch 98/100
35/35 [==============================] - 0s 685us/step - loss: 0.1162 - accuracy: 0.9619
Epoch 99/100
35/35 [==============================] - 0s 631us/step - loss: 0.1155 - accuracy: 0.9637
Epoch 100/100
35/35 [==============================] - 0s 645us/step - loss: 0.1141 - accuracy: 0.9637
12/12 - 0s - loss: 0.5093 - accuracy: 0.8424
Loss: 0.5092506408691406, Accuracy: 0.842391312122345

In [12]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.86.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)

print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.4509 - accuracy: 0.8641
Loss: 0.45085883140563965, Accuracy: 0.864130437374115

In [13]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")

In [14]:
# Import the model to a new object
nn_imported = tf.keras.models.load_model('trained_attrition.h5')

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.4509 - accuracy: 0.8641
Loss: 0.45085883140563965, Accuracy: 0.864130437374115